### PR TITLE
Migrate `example` to null safety, adopt `flutter_lints`

### PR DESCRIPTION
**Pull request by domesticmouse**

### CODE REVIEW

**Comment by shyndman** [comment]
Looks like I need to do some maintenance on CI.

**Comment by shyndman** [comment]
So @domesticmouse, what's your thinking behind adopting `flutter_lints` project-wide?

**Comment by domesticmouse** [comment]
Looks like you have Flutter 2.2 as your CI SDK: https://github.com/shyndman/flutter_layout_grid/runs/5344619625?check_suite_focus=true#step:4:37

As for migrating from a copy of pedantic 1.8 rule set to `flutter_lints`, we deprecated pedantic for a reason. For Flutter code like this library, `flutter_lints` captures all of our best practices for both dart code and flutter api usage.

**Comment by shyndman** [comment]
Ah, got it. 

So this is a bit too broadly applied for my liking. Want me to take over the PR, or go point for point?

**Comment by shyndman** [comment]
Thanks @domesticmouse! 👍

**Comment by shyndman** [comment]
[Published as `v1.0.5`](https://pub.dev/packages/flutter_layout_grid)

**Pull request merged**
